import { useState } from "react";
import {
  AlertTriangle,
  Bot,
  CheckCircle2,
  Loader2,
  Sparkles,
  Wand2,
} from "lucide-react";
import { useQwenAnalyze } from "@/lib/api";
import type { CaseDetail, QwenAnalysis } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export function QwenSynthesisPanel({ detail }: { detail: CaseDetail }) {
  const { case: c, qwen, findings, decision, evidence } = detail;
  const qwenMut = useQwenAnalyze();
  const [lastError, setLastError] = useState<string | null>(null);

  const canSynthesize = findings.length > 0;
  const canExplain = Boolean(decision);

  const generate = (type: "investigation_synthesis" | "resolution_explanation") => {
    setLastError(null);
    qwenMut.mutate(
      { caseId: c.id, type },
      {
        onError: (err) => setLastError(err.message),
      },
    );
  };

  const understanding = qwen?.complaint_understanding;
  const synthesis = qwen?.investigation_synthesis;
  const explanation = qwen?.resolution_explanation;

  const pendingType = qwenMut.isPending
    ? (qwenMut.variables?.type as string | undefined) ?? null
    : null;

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <p className="text-sm text-slate-500">
          Natural-language intelligence generated by Qwen — cached per case and
          reused.
        </p>
        <span className="flex items-center gap-1.5 rounded-full bg-cyan-50 px-2.5 py-1 text-[11px] font-semibold text-cyan-700">
          <Bot className="h-3.5 w-3.5" />
          Qwen · alibaba/qwen-3.8-max
        </span>
      </div>

      {lastError && (
        <div className="flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-[13px] text-rose-800">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>
            Qwen analysis failed: {lastError}. The deterministic ACAN findings are
            still available in the Investigation tab.
          </span>
        </div>
      )}

      {/* Complaint understanding */}
      <Section title="Complaint Understanding" status={understanding ? "ready" : "cached"} model={understanding?.model}>
        {understanding ? (
          <div className="space-y-3">
            <p className="text-sm leading-relaxed text-slate-700">{understanding.summary}</p>
            <div className="flex flex-wrap gap-2 text-xs">
              <Chip label="Classification" value={understanding.classification ?? "—"} />
              <Chip label="Priority hint" value={(understanding.priority_hint ?? "—").toUpperCase()} tone="amber" />
            </div>
            {understanding.customer_message && (
              <div className="rounded-lg border border-cyan-100 bg-cyan-50 p-3 text-[13px] text-slate-700">
                <span className="font-semibold text-cyan-700">Customer message: </span>
                {understanding.customer_message}
              </div>
            )}
          </div>
        ) : (
          <p className="text-sm text-slate-400">Generated automatically when the complaint is submitted.</p>
        )}
      </Section>

      {/* Investigation synthesis */}
      <Section
        title="Qwen Investigation Synthesis"
        status={synthesis ? "ready" : "pending"}
        model={synthesis?.model}
        action={
          !synthesis && canSynthesize ? (
            <Button
              size="sm"
              onClick={() => generate("investigation_synthesis")}
              disabled={qwenMut.isPending}
            >
              {pendingType === "investigation_synthesis" ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Wand2 className="h-4 w-4" />
              )}
              {pendingType === "investigation_synthesis" ? "Qwen is synthesizing…" : "Generate Qwen Synthesis"}
            </Button>
          ) : undefined
        }
      >
        {synthesis ? (
          <div className="space-y-3">
            <p className="text-sm leading-relaxed text-slate-700">{synthesis.summary}</p>
            <div className="grid gap-3 sm:grid-cols-2">
              <ListBlock
                title="Supporting evidence"
                items={synthesis.supporting_evidence ?? []}
                tone="emerald"
              />
              <ListBlock
                title="Contradicting evidence"
                items={synthesis.contradicting_evidence ?? []}
                tone="rose"
              />
            </div>
            {synthesis.root_cause && (
              <div className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-[13px] text-slate-700">
                <span className="font-semibold">Root cause: </span>
                {synthesis.root_cause}
              </div>
            )}
            <div className="flex flex-wrap gap-2 text-xs">
              <Chip label="Risk" value={(synthesis.risk ?? "—").toUpperCase()} tone={synthesis.risk === "high" ? "rose" : synthesis.risk === "medium" ? "amber" : "emerald"} />
              <Chip label="Recommended action" value={synthesis.recommended_action ?? "—"} />
            </div>
            {synthesis.confidence_explanation && (
              <p className="text-xs leading-relaxed text-slate-500">
                <span className="font-semibold text-slate-600">Confidence: </span>
                {synthesis.confidence_explanation}
              </p>
            )}
          </div>
        ) : canSynthesize ? (
          <p className="text-sm text-slate-400">
            Qwen has not synthesized this investigation yet. Generate once — the
            result is cached and reused.
          </p>
        ) : (
          <p className="text-sm text-slate-400">
            Run the ACAN investigation first to unlock Qwen synthesis.
          </p>
        )}
      </Section>

      {/* Resolution explanation */}
      <Section
        title="Resolution Explanation (customer-facing)"
        status={explanation ? "ready" : "pending"}
        model={explanation?.model}
        action={
          !explanation && canExplain ? (
            <Button
              size="sm"
              variant="success"
              onClick={() => generate("resolution_explanation")}
              disabled={qwenMut.isPending}
            >
              {pendingType === "resolution_explanation" ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Sparkles className="h-4 w-4" />
              )}
              {pendingType === "resolution_explanation" ? "Qwen is explaining…" : "Generate Resolution Message"}
            </Button>
          ) : undefined
        }
      >
        {explanation ? (
          <div className="space-y-3">
            {explanation.resolution_summary && (
              <p className="text-sm leading-relaxed text-slate-700">{explanation.resolution_summary}</p>
            )}
            {explanation.customer_message && (
              <div className="rounded-lg border border-emerald-100 bg-emerald-50 p-3 text-[13px] text-slate-700">
                <span className="font-semibold text-emerald-700">Customer message: </span>
                {explanation.customer_message}
              </div>
            )}
            {explanation.resolution_details && (
              <p className="text-xs leading-relaxed text-slate-500">{explanation.resolution_details}</p>
            )}
          </div>
        ) : canExplain ? (
          <p className="text-sm text-slate-400">
            Generate a customer-friendly explanation of the approved resolution.
          </p>
        ) : (
          <p className="text-sm text-slate-400">
            Becomes available once the case reaches the arbitration stage.
          </p>
        )}
      </Section>

      {!understanding && !synthesis && !explanation && (
        <div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 p-4 text-[13px] text-slate-500">
          <Sparkles className="h-4 w-4 text-cyan-600" />
          Qwen analyses are generated on demand and cached. {evidence.length} evidence items collected.
        </div>
      )}
    </div>
  );
}

function Section({
  title,
  status,
  model,
  action,
  children,
}: {
  title: string;
  status: string;
  model?: string;
  action?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="bg-card shadow-card rounded-xl border border-slate-200/80 p-5">
      <div className="flex flex-wrap items-center gap-2">
        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-cyan-500/15 to-blue-500/5 text-cyan-600">
          <Bot className="h-4 w-4" />
        </div>
        <h3 className="text-sm font-semibold text-slate-900">{title}</h3>
        <span
          className={cn(
            "rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide",
            status === "ready" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500",
          )}
        >
          {status === "ready" ? "Ready" : "Pending"}
        </span>
        {model && <span className="ml-auto font-mono text-[10px] text-slate-400">{model}</span>}
        {action && <span className="ml-auto">{action}</span>}
      </div>
      <div className="mt-4">{children}</div>
    </div>
  );
}

function ListBlock({ title, items, tone }: { title: string; items: string[]; tone: "emerald" | "rose" }) {
  if (items.length === 0) {
    return (
      <div className="rounded-lg border border-slate-100 bg-slate-50 p-3">
        <div className="text-xs font-semibold text-slate-500">{title}</div>
        <div className="mt-1 text-xs text-slate-400">None identified.</div>
      </div>
    );
  }
  return (
    <div className="rounded-lg border border-slate-100 bg-slate-50 p-3">
      <div className="text-xs font-semibold text-slate-500">{title}</div>
      <ul className="mt-1.5 space-y-1.5">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-2 text-xs text-slate-600">
            {tone === "emerald" ? (
              <CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-500" />
            ) : (
              <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-rose-500" />
            )}
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function Chip({ label, value, tone = "cyan" }: { label: string; value: string; tone?: string }) {
  const tones: Record<string, string> = {
    cyan: "bg-cyan-50 text-cyan-700",
    amber: "bg-amber-50 text-amber-700",
    emerald: "bg-emerald-50 text-emerald-700",
    rose: "bg-rose-50 text-rose-700",
  };
  return (
    <span className={`rounded-lg px-2.5 py-1 ${tones[tone]}`}>
      <span className="font-semibold">{label}: </span>
      {value}
    </span>
  );
}
